//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentingGown.Models
{<DirectedGraph xmlns="http://schemas.microsoft.com/vs/2009/dgml">
  <Nodes>
    <Node Id="(@1 @2)" Visibility="Hidden" />
    <Node Id="(@3 Namespace=RentingGown.Models Type=Areas)" Category="CodeSchema_Class" CodeSchemaProperty_IsPublic="True" CommonLabel="Areas" Icon="Microsoft.VisualStudio.Class.Public" IsDragSource="True" Label="Areas" SourceLocation="(Assembly=file:///C:/Users/User/Documents/GitHub/RentingGown/RentingGown/RentingGown/Models/Areas.cs StartLineNumber=14 StartCharacterOffset=25 EndLineNumber=14 EndCharacterOffset=30)" />
  </Nodes>
  <Links>
    <Link Source="(@1 @2)" Target="(@3 Namespace=RentingGown.Models Type=Areas)" Category="Contains" />
  </Links>
  <Categories>
    <Category Id="CodeSchema_Class" Label="Class" BasedOn="CodeSchema_Type" Icon="CodeSchema_Class" />
    <Category Id="CodeSchema_Type" Label="Type" Icon="CodeSchema_Class" />
    <Category Id="Contains" Label="Contains" Description="Whether the source of the link contains the target object" IsContainment="True" />
  </Categories>
  <Properties>
    <Property Id="CodeSchemaProperty_IsPublic" Label="Is Public" Description="Flag to indicate the scope is Public" DataType="System.Boolean" />
    <Property Id="CommonLabel" DataType="System.String" />
    <Property Id="Icon" Label="Icon" DataType="System.String" />
    <Property Id="IsContainment" DataType="System.Boolean" />
    <Property Id="IsDragSource" Label="IsDragSource" Description="IsDragSource" DataType="System.Boolean" />
    <Property Id="Label" Label="Label" Description="Displayable label of an Annotatable object" DataType="System.String" />
    <Property Id="SourceLocation" Label="Start Line Number" DataType="Microsoft.VisualStudio.GraphModel.CodeSchema.SourceLocation" />
    <Property Id="Visibility" Label="Visibility" Description="Defines whether a node in the graph is visible or not" DataType="System.Windows.Visibility" />
  </Properties>
  <QualifiedNames>
    <Name Id="Assembly" Label="Assembly" ValueType="Uri" />
    <Name Id="File" Label="File" ValueType="Uri" />
    <Name Id="Namespace" Label="Namespace" ValueType="System.String" />
    <Name Id="Type" Label="Type" ValueType="System.Object" />
  </QualifiedNames>
  <IdentifierAliases>
    <Alias n="1" Uri="Assembly=$(VsSolutionUri)/RentingGown/RentingGown.csproj" />
    <Alias n="2" Uri="File=$(VsSolutionUri)/RentingGown/Models/Areas.cs" />
    <Alias n="3" Uri="Assembly=$(d0d95baa-eb66-4204-93fc-cb42e9603d2d.OutputPathUri)" />
  </IdentifierAliases>
  <Paths>
    <Path Id="d0d95baa-eb66-4204-93fc-cb42e9603d2d.OutputPathUri" Value="file:///C:/Users/User/Documents/GitHub/RentingGown/RentingGown/RentingGown/bin/RentingGown.dll" />
    <Path Id="VsSolutionUri" Value="file:///C:/Users/User/Documents/GitHub/RentingGown/RentingGown" />
  </Paths>
</DirectedGraph>
    using System;
    using System.Collections.Generic;
    
    public partial class Areas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Areas()
        {
            this.Renters = new HashSet<Renters>();
            this.Tenants = new HashSet<Tenants>();
        }
    
        public int id_area { get; set; }
        public string area { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Renters> Renters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tenants> Tenants { get; set; }
    }
}
